name: Publish resume in JSONResume format as Github Page

on:
  push:
    branches: [ main ]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - name: JSONResume Export
        uses: kelvintaywl/action-jsonresume-export@v1
